# Generated by Django 4.0.2 on 2022-02-27 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('apellidoMaterno', models.CharField(max_length=100)),
                ('apellidoPaterno', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
        ),
        migrations.CreateModel(
            name='resultdoPrediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DatosSociodemograficos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('estado_civil', models.IntegerField(choices=[(3, 'Soltera'), (1, 'Casada'), ('', 'Estado civil'), (4, 'Viuda'), (2, 'Union libre')], default='')),
                ('escolaridad', models.IntegerField(choices=[(5, 'Posgrado'), (1, 'Primaria'), (2, 'Secundaria'), (3, 'Bachillerato'), ('', 'Escolaridad'), (4, 'Licenciatura')], default='')),
                ('ocupacion', models.IntegerField(choices=[(4, 'Desempleada'), ('', 'Ocupacion'), (1, 'Ama de casa'), (3, 'Estadiante'), (2, 'Empleada')], default='')),
                ('status_economico', models.IntegerField(choices=[('', 'Status economico'), (3, 'Media baja'), (4, 'Media alta'), (1, 'Baja baja'), (2, 'Baja alta')], default='')),
                ('ingreso_mensual', models.IntegerField()),
                ('embarazo_deseado', models.IntegerField(choices=[(2, 'No'), ('', 'Embarazo deseado'), (1, 'Si')], default='')),
                ('embarazo_planeado', models.IntegerField(choices=[(2, 'No'), ('', 'Embarazo planeado'), (1, 'Si')], default='')),
                ('parto_termino', models.IntegerField(choices=[(2, 'No'), ('', 'Parto término'), (1, 'Si')], default='')),
                ('paridad', models.IntegerField(choices=[(1, 'Primigesta'), ('', 'Paridad'), (2, 'Multigesta')], default='')),
                ('numero_de_hijos', models.IntegerField()),
                ('lactancia', models.IntegerField(choices=[(2, 'No'), ('', 'Lactancia'), (1, 'Si')], default='')),
                ('tiempo_de_lactancia', models.IntegerField()),
                ('enfermedad_del_neonato', models.IntegerField(choices=[(2, 'No'), ('', 'Enfermedad el neonato'), (1, 'Si')], default='')),
                ('tipo_de_enfermedad_neonato', models.IntegerField()),
                ('anestesia', models.IntegerField(choices=[(2, 'No'), ('', 'Anestesia'), (1, 'Si')], default='')),
                ('tipo_de_anestesia', models.IntegerField(choices=[(2, 'Anestesia general'), (1, 'Anestesia inhalatoria'), (0, 'Otra'), ('', 'Tipos de anestesia')], default='')),
                ('tipo_de_parto', models.IntegerField(choices=[(1, 'vaginal'), ('', 'Tipos de parto'), (2, 'Cesarea')], default='')),
                ('edad_del_bebe', models.IntegerField()),
                ('lugar_de_atencion', models.IntegerField()),
                ('apoyo_de_familia', models.IntegerField(choices=[(2, 'No'), ('', 'Apoyo actual de la familia'), (1, 'Si')], default='')),
                ('apoyo_de_pareja', models.IntegerField(choices=[(2, 'No'), ('', 'Apoyo actual de la Pareja'), (1, 'Si')], default='')),
                ('abortos', models.IntegerField(choices=[(2, 'No'), ('', 'Abortos previos al parto actual'), (1, 'Si')], default='')),
                ('numero_de_bortos', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CuestionarioEdimburgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta1', models.CharField(blank=True, choices=[('No tanto ahora', 'No tanto ahora'), ('Mucho menos', 'Mucho menos'), ('Tanto como siempre', 'Tanto como siempre'), ('No, no he podido', 'No, no he podido')], default='', max_length=100, null=True, verbose_name='1. He sido capaz de reír y ver el lado bueno de las cosas')),
                ('pregunta2', models.CharField(blank=True, choices=[('Algo menos de lo que solía hacer', 'Algo menos de lo que solía hacer'), ('Definitivamente menos', 'Definitivamente menos'), ('No, nada ', 'No, nada'), ('Tanto como siempre', 'Tanto como siempre')], default='', max_length=100, null=True, verbose_name='2. He mirado el futuro con placer')),
                ('pregunta3', models.CharField(blank=True, choices=[('No muy a menudo', 'No muy a menudo'), ('Sí, algunas veces', 'Sí, algunas veces'), ('Sí, la mayoría de las veces', 'Sí, la mayoría de las veces'), ('No, nunca', 'No, nunca')], default='', max_length=100, null=True, verbose_name='3. Me he culpado sin necesidad cuando las cosas no salían bien')),
                ('pregunta4', models.CharField(blank=True, choices=[('No, para nada', 'No, para nada'), ('Sí, a menudo', 'Sí, a menudo'), ('Sí, a veces', 'Sí, a veces'), ('Casi nada', 'Casi nada')], default='', max_length=100, null=True, verbose_name='4. He estado ansiosa y preocupada sin motivo')),
                ('pregunta5', models.CharField(blank=True, choices=[('Sí, bastante', 'Sí, bastante'), ('Sí, a veces', 'Sí, a veces'), ('No, nada', 'No, nada'), ('No, no mucho', 'No, no mucho')], default='', max_length=100, null=True, verbose_name='5. He sentido miedo y pánico sin motivo alguno')),
                ('pregunta6', models.CharField(blank=True, choices=[('No, casi nunca', 'No, casi nunca'), ('Sí, la mayor parte de las veces', 'Sí, la mayor parte de las veces'), ('Sí, a veces', 'Sí, a veces'), ('No, nada', 'No, nada')], default='', max_length=100, null=True, verbose_name='6. Las cosas me oprimen o agobian')),
                ('pregunta7', models.CharField(blank=True, choices=[('No muy a menudo', 'No muy a menudo'), ('Sí, a veces', 'Sí, a veces'), ('Sí, la mayoría de las veces', 'Sí, la mayoría de las veces'), ('No, nada', 'No, nada')], default='', max_length=100, null=True, verbose_name='7. Me he sentido tan infeliz que he tenido dificultad para dormir')),
                ('pregunta8', models.CharField(blank=True, choices=[('No muy a menudo', 'No muy a menudo'), ('Sí, bastante a menudo', 'Sí, bastante a menudo'), ('No, nada', 'No, nada'), ('Sí, casi siempre', 'Sí, casi siempre')], default='', max_length=100, null=True, verbose_name='8. Me he sentido triste y desgraciada')),
                ('pregunta9', models.CharField(blank=True, choices=[('No, nunca', 'No, nunca'), ('Sí, bastante a menudo', 'Sí, bastante a menudo'), ('Sólo en ocasiones', 'Sólo en ocasiones'), ('Sí, casi siempre', 'Sí, casi siempre')], default='', max_length=100, null=True, verbose_name='9. He sido tan infeliz que he estado llorando')),
                ('pregunta10', models.CharField(blank=True, choices=[('A veces', 'A veces'), ('Sí, bastante a menudo', 'Sí, bastante a menudo'), ('Casi nunca', 'Casi nunca'), ('No, nunca', 'No, nunca')], default='', max_length=100, null=True, verbose_name='10. He pensado en hacerme daño a mí misma')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
