# Generated by Django 4.0.2 on 2022-02-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta1',
            field=models.CharField(blank=True, choices=[('No tanto ahora', 'No tanto ahora'), ('No, no he podido', 'No, no he podido'), ('Mucho menos', 'Mucho menos'), ('Tanto como siempre', 'Tanto como siempre')], default='', max_length=100, null=True, verbose_name='1. He sido capaz de reír y ver el lado bueno de las cosas'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta10',
            field=models.CharField(blank=True, choices=[('Casi nunca', 'Casi nunca'), ('No, nunca', 'No, nunca'), ('Sí, bastante a menudo', 'Sí, bastante a menudo'), ('A veces', 'A veces')], default='', max_length=100, null=True, verbose_name='10. He pensado en hacerme daño a mí misma'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta2',
            field=models.CharField(blank=True, choices=[('Tanto como siempre', 'Tanto como siempre'), ('Definitivamente menos', 'Definitivamente menos'), ('Algo menos de lo que solía hacer', 'Algo menos de lo que solía hacer'), ('No, nada ', 'No, nada')], default='', max_length=100, null=True, verbose_name='2. He mirado el futuro con placer'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta3',
            field=models.CharField(blank=True, choices=[('Sí, la mayoría de las veces', 'Sí, la mayoría de las veces'), ('Sí, algunas veces', 'Sí, algunas veces'), ('No muy a menudo', 'No muy a menudo'), ('No, nunca', 'No, nunca')], default='', max_length=100, null=True, verbose_name='3. Me he culpado sin necesidad cuando las cosas no salían bien'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta4',
            field=models.CharField(blank=True, choices=[('Sí, a veces', 'Sí, a veces'), ('No, para nada', 'No, para nada'), ('Sí, a menudo', 'Sí, a menudo'), ('Casi nada', 'Casi nada')], default='', max_length=100, null=True, verbose_name='4. He estado ansiosa y preocupada sin motivo'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta5',
            field=models.CharField(blank=True, choices=[('No, no mucho', 'No, no mucho'), ('Sí, bastante', 'Sí, bastante'), ('No, nada', 'No, nada'), ('Sí, a veces', 'Sí, a veces')], default='', max_length=100, null=True, verbose_name='5. He sentido miedo y pánico sin motivo alguno'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta6',
            field=models.CharField(blank=True, choices=[('Sí, la mayor parte de las veces', 'Sí, la mayor parte de las veces'), ('No, casi nunca', 'No, casi nunca'), ('No, nada', 'No, nada'), ('Sí, a veces', 'Sí, a veces')], default='', max_length=100, null=True, verbose_name='6. Las cosas me oprimen o agobian'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta7',
            field=models.CharField(blank=True, choices=[('Sí, la mayoría de las veces', 'Sí, la mayoría de las veces'), ('No muy a menudo', 'No muy a menudo'), ('No, nada', 'No, nada'), ('Sí, a veces', 'Sí, a veces')], default='', max_length=100, null=True, verbose_name='7. Me he sentido tan infeliz que he tenido dificultad para dormir'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta8',
            field=models.CharField(blank=True, choices=[('Sí, bastante a menudo', 'Sí, bastante a menudo'), ('No muy a menudo', 'No muy a menudo'), ('No, nada', 'No, nada'), ('Sí, casi siempre', 'Sí, casi siempre')], default='', max_length=100, null=True, verbose_name='8. Me he sentido triste y desgraciada'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta9',
            field=models.CharField(blank=True, choices=[('Sí, bastante a menudo', 'Sí, bastante a menudo'), ('Sólo en ocasiones', 'Sólo en ocasiones'), ('No, nunca', 'No, nunca'), ('Sí, casi siempre', 'Sí, casi siempre')], default='', max_length=100, null=True, verbose_name='9. He sido tan infeliz que he estado llorando'),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='abortos',
            field=models.IntegerField(choices=[('', 'Abortos previos al parto actual'), (1, 'Si'), (2, 'No')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='anestesia',
            field=models.IntegerField(choices=[('', 'Anestesia'), (1, 'Si'), (2, 'No')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='apoyo_de_familia',
            field=models.IntegerField(choices=[('', 'Apoyo actual de la familia'), (1, 'Si'), (2, 'No')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='apoyo_de_pareja',
            field=models.IntegerField(choices=[('', 'Apoyo actual de la Pareja'), (1, 'Si'), (2, 'No')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='embarazo_deseado',
            field=models.IntegerField(choices=[('', 'Embarazo deseado'), (1, 'Si'), (2, 'No')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='embarazo_planeado',
            field=models.IntegerField(choices=[(2, 'No'), (1, 'Si'), ('', 'Embarazo planeado')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='enfermedad_del_neonato',
            field=models.IntegerField(choices=[('', 'Enfermedad el neonato'), (1, 'Si'), (2, 'No')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='escolaridad',
            field=models.IntegerField(choices=[(3, 'Bachillerato'), (4, 'Licenciatura'), (2, 'Secundaria'), (5, 'Posgrado'), ('', 'Escolaridad'), (1, 'Primaria')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='estado_civil',
            field=models.IntegerField(choices=[('', 'Estado civil'), (4, 'Viuda'), (3, 'Soltera'), (1, 'Casada'), (2, 'Union libre')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='lactancia',
            field=models.IntegerField(choices=[('', 'Lactancia'), (1, 'Si'), (2, 'No')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='ocupacion',
            field=models.IntegerField(choices=[(4, 'Desempleada'), (1, 'Ama de casa'), (2, 'Empleada'), ('', 'Ocupacion'), (3, 'Estadiante')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='parto_termino',
            field=models.IntegerField(choices=[('', 'Parto término'), (1, 'Si'), (2, 'No')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='status_economico',
            field=models.IntegerField(choices=[(3, 'Media baja'), (4, 'Media alta'), ('', 'Status economico'), (1, 'Baja baja'), (2, 'Baja alta')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='tipo_de_anestesia',
            field=models.IntegerField(choices=[('', 'Tipos de anestesia'), (0, 'Otra'), (1, 'Anestesia inhalatoria'), (2, 'Anestesia general')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='tipo_de_parto',
            field=models.IntegerField(choices=[('', 'Tipos de parto'), (1, 'vaginal'), (2, 'Cesarea')], default=''),
        ),
    ]
