# Generated by Django 4.0.2 on 2022-02-13 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosSociodemograficos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('estado_civil', models.CharField(blank=True, choices=[('Soltera', 'Soltera'), ('Casada', 'Casada'), ('', 'Estado civil'), ('Union libre', 'Union libre'), ('Viuda', 'Viuda')], default='', max_length=20, null=True)),
                ('escolaridad', models.CharField(blank=True, choices=[('Lienciatura', 'Licenciatura'), ('Bachillerato', 'Bachillerato'), ('', 'Escolaridad'), ('Posgrado', 'Posgrado'), ('Secundaria', 'Secundaria'), ('Primaria', 'Primaria')], default='', max_length=50, null=True)),
                ('embarazo_planeado', models.CharField(blank=True, choices=[('', 'Embarazo planeado'), ('Si', 'Si'), ('No', 'No')], default='', max_length=10, null=True)),
                ('embarazo_deseado', models.CharField(blank=True, choices=[('', 'Embarazo deseado'), ('Si', 'Si'), ('No', 'No')], default='', max_length=10, null=True)),
                ('parto_termino', models.CharField(blank=True, choices=[('Término temprano', 'Término temprano'), ('', 'Parto término'), ('Postérmino', 'Postérmino'), ('Término completo', 'Término completo'), ('Término tardío', 'Término tardío')], default='', max_length=30, null=True)),
                ('paridad', models.IntegerField()),
                ('numero_de_hijos', models.IntegerField()),
                ('lactancia', models.CharField(blank=True, choices=[('Si', 'Si'), ('', 'Lactancia'), ('No', 'No')], default='', max_length=30, null=True)),
                ('tiempo_de_lactancia', models.IntegerField()),
                ('enfermedad_del_neonato', models.CharField(blank=True, choices=[('Si', 'Si'), ('', 'Enfermedad el neonato'), ('No', 'No')], default='', max_length=30, null=True)),
                ('tipo_de_enfermedad_neonato', models.CharField(max_length=150)),
                ('anestesia', models.CharField(blank=True, choices=[('Si', 'Si'), ('', 'Anestesia'), ('No', 'No')], default='', max_length=30, null=True)),
                ('tipo_de_anestesia', models.CharField(blank=True, choices=[('Bloqueo espinal (epidural y subaracnoideo)', 'Bloqueo espinal (epidural y subaracnoideo)'), ('Analgesia local', 'Analgesia local'), ('Analgesia parenteral (intramuscular o intravenosa)', 'Analgesia parenteral (intramuscular o intravenosa)'), ('Bloqueo paracervical', 'Bloqueo paracervical'), ('', 'Tipos de anestesia'), ('Bloqueo de nervios pudendos', 'Bloqueo de nervios pudendos'), ('Anestesia general', 'Anestesia general'), ('Anestesia inhalatoria', 'Anestesia inhalatoria')], default='', max_length=100, null=True)),
                ('tipo_de_parto', models.CharField(blank=True, choices=[('', 'Tipos de parto'), ('Parto espontáneo', 'Parto espontáneo'), ('Parto inducido', 'Parto inducido')], default='', max_length=50, null=True)),
                ('edad_del_bebe', models.IntegerField()),
                ('lugar_de_atencion', models.CharField(max_length=150)),
                ('apoyo_de_familia', models.CharField(blank=True, choices=[('Si', 'Si'), ('', 'Apoyo actual de la familia'), ('No', 'No')], default='', max_length=50, null=True)),
                ('apoyo_de_pareja', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('', 'Apoyo actual de la Pareja')], default='', max_length=50, null=True)),
                ('abortos_previos', models.CharField(blank=True, choices=[('Si', 'Si'), ('', 'Abortos previos al parto actual'), ('No', 'No')], default='', max_length=50, null=True)),
                ('numero_de_bortos', models.IntegerField()),
                ('ocupacion', models.CharField(blank=True, choices=[('Empleada tiempo completo', 'Empleada tiempo completo'), ('Desempleada', 'Desempleada'), ('Empleada tiempo parcial', 'Empleada tiempo parcial'), ('', 'Ocupacion'), ('Ama de casa', 'Ama de casa')], default='', max_length=50, null=True)),
                ('status_economico', models.CharField(blank=True, choices=[('Baja', 'Baja'), ('', 'Status economico'), ('Alta', 'Alta'), ('Media', 'Media')], default='', max_length=50, null=True)),
                ('ingreso_mensual', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CuestionarioEdimburgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta1', models.CharField(blank=True, choices=[('No tanto ahora', 'No tanto ahora'), ('No, no he podido', 'No, no he podido'), ('Mucho menos', 'Mucho menos'), ('Tanto como siempre', 'Tanto como siempre')], default='', max_length=100, null=True, verbose_name='1. He sido capaz de reír y ver el lado bueno de las cosas')),
                ('pregunta2', models.CharField(blank=True, choices=[('No, nada ', 'No, nada'), ('Tanto como siempre', 'Tanto como siempre'), ('Definitivamente menos', 'Definitivamente menos'), ('Algo menos de lo que solía hacer', 'Algo menos de lo que solía hacer')], default='', max_length=100, null=True, verbose_name='2. He mirado el futuro con placer')),
                ('pregunta3', models.CharField(blank=True, choices=[('No muy a menudo', 'No muy a menudo'), ('Sí, la mayoría de las veces', 'Sí, la mayoría de las veces'), ('No, nunca', 'No, nunca'), ('Sí, algunas veces', 'Sí, algunas veces')], default='', max_length=100, null=True, verbose_name='3. Me he culpado sin necesidad cuando las cosas no salían bien')),
                ('pregunta4', models.CharField(blank=True, choices=[('No, para nada', 'No, para nada'), ('Sí, a menudo', 'Sí, a menudo'), ('Casi nada', 'Casi nada'), ('Sí, a veces', 'Sí, a veces')], default='', max_length=100, null=True, verbose_name='4. He estado ansiosa y preocupada sin motivo')),
                ('pregunta5', models.CharField(blank=True, choices=[('Sí, bastante', 'Sí, bastante'), ('No, nada', 'No, nada'), ('Sí, a veces', 'Sí, a veces'), ('No, no mucho', 'No, no mucho')], default='', max_length=100, null=True, verbose_name='5. He sentido miedo y pánico sin motivo alguno')),
                ('pregunta6', models.CharField(blank=True, choices=[('No, nada', 'No, nada'), ('Sí, a veces', 'Sí, a veces'), ('No, casi nunca', 'No, casi nunca'), ('Sí, la mayor parte de las veces', 'Sí, la mayor parte de las veces')], default='', max_length=100, null=True, verbose_name='6. Las cosas me oprimen o agobian')),
                ('pregunta7', models.CharField(blank=True, choices=[('No muy a menudo', 'No muy a menudo'), ('Sí, la mayoría de las veces', 'Sí, la mayoría de las veces'), ('No, nada', 'No, nada'), ('Sí, a veces', 'Sí, a veces')], default='', max_length=100, null=True, verbose_name='7. Me he sentido tan infeliz que he tenido dificultad para dormir')),
                ('pregunta8', models.CharField(blank=True, choices=[('Sí, casi siempre', 'Sí, casi siempre'), ('Sí, bastante a menudo', 'Sí, bastante a menudo'), ('No, nada', 'No, nada'), ('No muy a menudo', 'No muy a menudo')], default='', max_length=100, null=True, verbose_name='8. Me he sentido triste y desgraciada')),
                ('pregunta9', models.CharField(blank=True, choices=[('Sí, casi siempre', 'Sí, casi siempre'), ('Sí, bastante a menudo', 'Sí, bastante a menudo'), ('No, nunca', 'No, nunca'), ('Sólo en ocasiones', 'Sólo en ocasiones')], default='', max_length=100, null=True, verbose_name='9. He sido tan infeliz que he estado llorando')),
                ('pregunta10', models.CharField(blank=True, choices=[('A veces', 'A veces'), ('Sí, bastante a menudo', 'Sí, bastante a menudo'), ('No, nunca', 'No, nunca'), ('Casi nunca', 'Casi nunca')], default='', max_length=100, null=True, verbose_name='10. He pensado en hacerme daño a mí misma')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
