# Generated by Django 4.0.2 on 2022-02-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cuestionarioedimburgo_pregunta1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta1',
            field=models.CharField(blank=True, choices=[('No tanto ahora', 'No tanto ahora'), ('Tanto como siempre', 'Tanto como siempre'), ('Mucho menos', 'Mucho menos'), ('No, no he podido', 'No, no he podido')], default='', max_length=100, null=True, verbose_name='1. He sido capaz de reír y ver el lado bueno de las cosas'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta10',
            field=models.CharField(blank=True, choices=[('No, nunca', 'No, nunca'), ('Casi nunca', 'Casi nunca'), ('Sí, bastante a menudo', 'Sí, bastante a menudo'), ('A veces', 'A veces')], default='', max_length=100, null=True, verbose_name='10. He pensado en hacerme daño a mí misma'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta2',
            field=models.CharField(blank=True, choices=[('Algo menos de lo que solía hacer', 'Algo menos de lo que solía hacer'), ('Tanto como siempre', 'Tanto como siempre'), ('No, nada ', 'No, nada'), ('Definitivamente menos', 'Definitivamente menos')], default='', max_length=100, null=True, verbose_name='2. He mirado el futuro con placer'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta3',
            field=models.CharField(blank=True, choices=[('No, nunca', 'No, nunca'), ('No muy a menudo', 'No muy a menudo'), ('Sí, algunas veces', 'Sí, algunas veces'), ('Sí, la mayoría de las veces', 'Sí, la mayoría de las veces')], default='', max_length=100, null=True, verbose_name='3. Me he culpado sin necesidad cuando las cosas no salían bien'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta4',
            field=models.CharField(blank=True, choices=[('Sí, a veces', 'Sí, a veces'), ('Casi nada', 'Casi nada'), ('No, para nada', 'No, para nada'), ('Sí, a menudo', 'Sí, a menudo')], default='', max_length=100, null=True, verbose_name='4. He estado ansiosa y preocupada sin motivo'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta5',
            field=models.CharField(blank=True, choices=[('Sí, a veces', 'Sí, a veces'), ('No, nada', 'No, nada'), ('Sí, bastante', 'Sí, bastante'), ('No, no mucho', 'No, no mucho')], default='', max_length=100, null=True, verbose_name='5. He sentido miedo y pánico sin motivo alguno'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta6',
            field=models.CharField(blank=True, choices=[('Sí, a veces', 'Sí, a veces'), ('No, nada', 'No, nada'), ('No, casi nunca', 'No, casi nunca'), ('Sí, la mayor parte de las veces', 'Sí, la mayor parte de las veces')], default='', max_length=100, null=True, verbose_name='6. Las cosas me oprimen o agobian'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta7',
            field=models.CharField(blank=True, choices=[('Sí, a veces', 'Sí, a veces'), ('No, nada', 'No, nada'), ('No muy a menudo', 'No muy a menudo'), ('Sí, la mayoría de las veces', 'Sí, la mayoría de las veces')], default='', max_length=100, null=True, verbose_name='7. Me he sentido tan infeliz que he tenido dificultad para dormir'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta8',
            field=models.CharField(blank=True, choices=[('No, nada', 'No, nada'), ('No muy a menudo', 'No muy a menudo'), ('Sí, bastante a menudo', 'Sí, bastante a menudo'), ('Sí, casi siempre', 'Sí, casi siempre')], default='', max_length=100, null=True, verbose_name='8. Me he sentido triste y desgraciada'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta9',
            field=models.CharField(blank=True, choices=[('No, nunca', 'No, nunca'), ('Sí, casi siempre', 'Sí, casi siempre'), ('Sí, bastante a menudo', 'Sí, bastante a menudo'), ('Sólo en ocasiones', 'Sólo en ocasiones')], default='', max_length=100, null=True, verbose_name='9. He sido tan infeliz que he estado llorando'),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='apoyo_de_pareja',
            field=models.IntegerField(choices=[(2, 'No'), (1, 'Si'), ('', 'Apoyo actual de la Pareja')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='embarazo_deseado',
            field=models.IntegerField(choices=[(2, 'No'), (1, 'Si'), ('', 'Embarazo deseado')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='embarazo_planeado',
            field=models.IntegerField(choices=[(1, 'Si'), (2, 'No'), ('', 'Embarazo planeado')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='enfermedad_del_neonato',
            field=models.IntegerField(choices=[('', 'Enfermedad el neonato'), (2, 'No'), (1, 'Si')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='escolaridad',
            field=models.IntegerField(choices=[(1, 'Primaria'), (4, 'Licenciatura'), (2, 'Secundaria'), (3, 'Bachillerato'), ('', 'Escolaridad'), (5, 'Posgrado')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='estado_civil',
            field=models.IntegerField(choices=[(4, 'Viuda'), (1, 'Casada'), (2, 'Union libre'), ('', 'Estado civil'), (3, 'Soltera')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='lactancia',
            field=models.IntegerField(choices=[('', 'Lactancia'), (2, 'No'), (1, 'Si')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='ocupacion',
            field=models.IntegerField(choices=[('', 'Ocupacion'), (1, 'Ama de casa'), (2, 'Empleada'), (4, 'Desempleada'), (3, 'Estadiante')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='paridad',
            field=models.IntegerField(choices=[(2, 'Multigesta'), (1, 'Primigesta'), ('', 'Paridad')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='parto_termino',
            field=models.IntegerField(choices=[('', 'Parto término'), (2, 'No'), (1, 'Si')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='status_economico',
            field=models.IntegerField(choices=[(4, 'Media alta'), ('', 'Status economico'), (1, 'Baja baja'), (3, 'Media baja'), (2, 'Baja alta')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='tipo_de_anestesia',
            field=models.IntegerField(choices=[('', 'Tipos de anestesia'), (2, 'Anestesia general'), (1, 'Anestesia inhalatoria'), (0, 'Otra')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='tipo_de_parto',
            field=models.IntegerField(choices=[(2, 'Cesarea'), ('', 'Tipos de parto'), (1, 'vaginal')], default=''),
        ),
    ]
