# Generated by Django 4.0.2 on 2022-02-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cuestionarioedimburgo_pregunta1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta1',
            field=models.IntegerField(blank=True, choices=[(4, 'No, Nada'), (2, 'No tanto ahora'), (3, 'Mucho menos ahora'), (1, 'Tanto como siempre')], default='', null=True, verbose_name='1. He sido capaz de reír y ver el lado bueno de las cosas'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta10',
            field=models.IntegerField(blank=True, choices=[(2, 'A veces'), (4, 'No, nunca'), (1, 'Sí, bastante a menudo'), (3, 'Casi nunca')], default='', null=True, verbose_name='10. He pensado en hacerme daño a mí misma'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta2',
            field=models.IntegerField(blank=True, choices=[(4, 'Casi nada'), (2, 'Meno que antes'), (3, 'Mucho menos que antes'), (1, 'Tanto como siempre')], default='', null=True, verbose_name='2. He mirado el futuro con placer'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta3',
            field=models.IntegerField(blank=True, choices=[(3, 'No muy a menudo'), (2, 'Sí, algunas veces'), (1, 'Sí, la mayoría de las veces'), (4, 'No, nunca')], default='', null=True, verbose_name='3. Me he culpado sin necesidad cuando las cosas no salían bien'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta4',
            field=models.IntegerField(blank=True, choices=[(4, 'Sí, a menudo'), (2, 'Casi nada'), (1, 'No, para nada'), (3, 'Sí, a veces')], default='', null=True, verbose_name='4. He estado ansiosa y preocupada sin motivo'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta5',
            field=models.IntegerField(blank=True, choices=[(4, 'No, nada'), (3, 'No, no mucho'), (2, 'Sí, a veces'), (1, 'Sí, bastante')], default='', null=True, verbose_name='5. He sentido miedo y pánico sin motivo alguno'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta6',
            field=models.IntegerField(blank=True, choices=[(4, 'No, nada'), (1, 'Sí, la mayor parte de las veces'), (3, 'No, casi nunca'), (2, 'Sí, a veces')], default='', null=True, verbose_name='6. Las cosas me oprimen o agobian'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta7',
            field=models.IntegerField(blank=True, choices=[(4, 'No, nada'), (3, 'No muy a menudo'), (1, 'Sí, la mayoría de las veces'), (2, 'Sí, a veces')], default='', null=True, verbose_name='7. Me he sentido tan infeliz que he tenido dificultad para dormir'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta8',
            field=models.IntegerField(blank=True, choices=[(4, 'No, nada'), (3, 'No muy a menudo'), (2, 'Sí, bastante a menudo'), (1, 'Sí, casi siempre')], default='', null=True, verbose_name='8. Me he sentido triste y desgraciada'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta9',
            field=models.IntegerField(blank=True, choices=[(2, 'Sí, bastante a menudo'), (4, 'No, nunca'), (3, 'Sólo en ocasiones'), (1, 'Sí, casi siempre')], default='', null=True, verbose_name='9. He sido tan infeliz que he estado llorando'),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='abortos',
            field=models.IntegerField(choices=[(1, 'Si'), ('', 'Abortos previos al parto actual'), (2, 'No')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='anestesia',
            field=models.IntegerField(choices=[(1, 'Si'), ('', 'Anestesia'), (2, 'No')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='apoyo_de_familia',
            field=models.IntegerField(choices=[(1, 'Si'), ('', 'Apoyo actual de la familia'), (2, 'No')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='apoyo_de_pareja',
            field=models.IntegerField(choices=[(1, 'Si'), (2, 'No'), ('', 'Apoyo actual de la Pareja')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='embarazo_deseado',
            field=models.IntegerField(choices=[(1, 'Si'), ('', 'Embarazo deseado'), (2, 'No')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='embarazo_planeado',
            field=models.IntegerField(choices=[(1, 'Si'), ('', 'Embarazo planeado'), (2, 'No')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='enfermedad_del_neonato',
            field=models.IntegerField(choices=[(1, 'Si'), ('', 'Enfermedad el neonato'), (2, 'No')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='escolaridad',
            field=models.IntegerField(choices=[(3, 'Bachillerato'), (2, 'Secundaria'), (4, 'Licenciatura'), (1, 'Primaria'), (5, 'Posgrado'), ('', 'Escolaridad')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='estado_civil',
            field=models.IntegerField(choices=[(3, 'Soltera'), (4, 'Viuda'), ('', 'Estado civil'), (2, 'Union libre'), (1, 'Casada')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='lactancia',
            field=models.IntegerField(choices=[(1, 'Si'), ('', 'Lactancia'), (2, 'No')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='ocupacion',
            field=models.IntegerField(choices=[(2, 'Empleada'), ('', 'Ocupacion'), (4, 'Desempleada'), (1, 'Ama de casa'), (3, 'Estadiante')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='paridad',
            field=models.IntegerField(choices=[(1, 'Primigesta'), ('', 'Paridad'), (2, 'Multigesta')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='parto_termino',
            field=models.IntegerField(choices=[('', 'Parto término'), (1, 'Si'), (2, 'No')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='status_economico',
            field=models.IntegerField(choices=[(3, 'Media baja'), ('', 'Status economico'), (2, 'Baja alta'), (1, 'Baja baja'), (4, 'Media alta')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='tipo_de_anestesia',
            field=models.IntegerField(choices=[(0, 'Otra'), ('', 'Tipos de anestesia'), (2, 'Anestesia general'), (1, 'Anestesia inhalatoria')], default=''),
        ),
    ]
