# Generated by Django 4.0.2 on 2022-02-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cuestionarioedimburgo_estadoactual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='estadoActual',
            field=models.CharField(blank=True, choices=[(2, 'Casi nunca'), (1, 'A veces'), (3, 'No, nunca'), (0, 'Sí, bastante a menudo')], default='', max_length=50, null=True, verbose_name='¿Está embarazada o hace poco tuvo un bebé?'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta1',
            field=models.IntegerField(blank=True, choices=[(1, 'No tanto ahora'), (0, 'Tanto como siempre'), (2, 'Mucho menos ahora'), (3, 'No, Nada')], default='', null=True, verbose_name='1. He sido capaz de reír y ver el lado bueno de las cosas'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta10',
            field=models.IntegerField(blank=True, choices=[(2, 'Casi nunca'), (1, 'A veces'), (3, 'No, nunca'), (0, 'Sí, bastante a menudo')], default='', null=True, verbose_name='10. He pensado en hacerme daño a mí misma'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta2',
            field=models.IntegerField(blank=True, choices=[(3, 'Casi nada'), (0, 'Tanto como siempre'), (2, 'Mucho menos que antes'), (1, 'Meno que antes')], default='', null=True, verbose_name='2. He mirado el futuro con placer'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta3',
            field=models.IntegerField(blank=True, choices=[(0, 'Sí, la mayoría de las veces'), (2, 'No muy a menudo'), (1, 'Sí, algunas veces'), (3, 'No, nunca')], default='', null=True, verbose_name='3. Me he culpado sin necesidad cuando las cosas no salían bien'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta4',
            field=models.IntegerField(blank=True, choices=[(3, 'Sí, a menudo'), (2, 'Sí, a veces'), (1, 'Casi nada'), (0, 'No, para nada')], default='', null=True, verbose_name='4. He estado ansiosa y preocupada sin motivo'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta5',
            field=models.IntegerField(blank=True, choices=[(2, 'No, no mucho'), (3, 'No, nada'), (0, 'Sí, bastante'), (1, 'Sí, a veces')], default='', null=True, verbose_name='5. He sentido miedo y pánico sin motivo alguno'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta6',
            field=models.IntegerField(blank=True, choices=[(2, 'No, casi nunca'), (3, 'No, nada'), (1, 'Sí, a veces'), (0, 'Sí, la mayor parte de las veces')], default='', null=True, verbose_name='6. Las cosas me oprimen o agobian'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta8',
            field=models.IntegerField(blank=True, choices=[(0, 'Sí, casi siempre'), (2, 'No muy a menudo'), (3, 'No, nada'), (1, 'Sí, bastante a menudo')], default='', null=True, verbose_name='8. Me he sentido triste y desgraciada'),
        ),
        migrations.AlterField(
            model_name='cuestionarioedimburgo',
            name='pregunta9',
            field=models.IntegerField(blank=True, choices=[(0, 'Sí, casi siempre'), (1, 'Sí, bastante a menudo'), (2, 'Sólo en ocasiones'), (3, 'No, nunca')], default='', null=True, verbose_name='9. He sido tan infeliz que he estado llorando'),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='abortos',
            field=models.IntegerField(choices=[(1, 'Si'), (2, 'No'), ('', 'Abortos previos al parto actual')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='anestesia',
            field=models.IntegerField(choices=[(1, 'Si'), (2, 'No'), ('', 'Anestesia')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='apoyo_de_familia',
            field=models.IntegerField(choices=[(1, 'Si'), (2, 'No'), ('', 'Apoyo actual de la familia')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='apoyo_de_pareja',
            field=models.IntegerField(choices=[(1, 'Si'), ('', 'Apoyo actual de la Pareja'), (2, 'No')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='embarazo_deseado',
            field=models.IntegerField(choices=[(1, 'Si'), (2, 'No'), ('', 'Embarazo deseado')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='embarazo_planeado',
            field=models.IntegerField(choices=[('', 'Embarazo planeado'), (2, 'No'), (1, 'Si')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='enfermedad_del_neonato',
            field=models.IntegerField(choices=[(1, 'Si'), (2, 'No'), ('', 'Enfermedad el neonato')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='escolaridad',
            field=models.IntegerField(choices=[(1, 'Primaria'), (4, 'Licenciatura'), (3, 'Bachillerato'), (5, 'Posgrado'), ('', 'Escolaridad'), (2, 'Secundaria')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='estado_civil',
            field=models.IntegerField(choices=[('', 'Estado civil'), (4, 'Viuda'), (3, 'Soltera'), (2, 'Union libre'), (1, 'Casada')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='lactancia',
            field=models.IntegerField(choices=[(1, 'Si'), (2, 'No'), ('', 'Lactancia')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='ocupacion',
            field=models.IntegerField(choices=[(1, 'Ama de casa'), (2, 'Empleada'), (4, 'Desempleada'), (3, 'Estadiante'), ('', 'Ocupacion')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='paridad',
            field=models.IntegerField(choices=[('', 'Paridad'), (1, 'Primigesta'), (2, 'Multigesta')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='parto_termino',
            field=models.IntegerField(choices=[(1, 'Si'), ('', 'Parto término'), (2, 'No')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='status_economico',
            field=models.IntegerField(choices=[('', 'Status economico'), (3, 'Media baja'), (2, 'Baja alta'), (4, 'Media alta'), (1, 'Baja baja')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='tipo_de_anestesia',
            field=models.IntegerField(choices=[(1, 'Anestesia inhalatoria'), ('', 'Tipos de anestesia'), (0, 'Otra'), (2, 'Anestesia general')], default=''),
        ),
        migrations.AlterField(
            model_name='datossociodemograficos',
            name='tipo_de_parto',
            field=models.IntegerField(choices=[('', 'Tipos de parto'), (1, 'vaginal'), (2, 'Cesarea')], default=''),
        ),
    ]
